---
# Temporary theme-check configuration for local iteration.
# Disable a couple of noisy checks so we can focus on other offenses.
root: "."
ignore:
  - node_modules/*

UnknownFilter:
  enabled: false

SchemaJsonFormat:
  enabled: false
